### PR TITLE
ENTESB-6123 - Add missing xmlns for blueprint

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
related to https://github.com/jboss-fuse/fabric8/pull/786

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
This is invalid, because the source of the quickstarts will come from fabric8 so no need to push changes directly on Fuse.

**Comment by apupier** [comment]
@oscerd Are you sure? During yesterday talk on IRC, we said that as it was after the code freeze, this repsoitory will also need to have the fix waiting for the next service release

**Comment by oscerd** [comment]
I don't think Fuse repository is included, maybe the it was the quickstarts repository.

Anyway, I'm reopening and we will wait for @janstey :-)

**Comment by oscerd** [comment]
Oh. My mistake. You're right, we are on quickstarts! ahahaah :-D

**Comment by oscerd** [comment]
Sorry about this. Merging it now!

**Pull request merged**
