### PR TITLE
ENTESB-6119 - Fix Camel CXF xsd location

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by oscerd** [comment]
Same story here, the quickstarts will come directly from fabric8 cxf quickstarts, so this is not needed.

We need to merge this https://github.com/jboss-fuse/fabric8/pull/785

**Comment by oscerd** [comment]
@apupier, can you rebase this one too?

**Comment by apupier** [comment]
rebased

**Comment by oscerd** [comment]
thanks

**Pull request merged**
